version: "2"

services:
  boot-app:
    image: "boot-mongo-docker"
    ports:
      - "8086:8086"
      - "5551:5551"
  mongo:
    image: "mongo"
    ports:
      - "27017:27019"
    volumes:
    - './data:/data/db'
  angular: # name of the first service
    build: "src/main/resources/static/personal-site" # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port forewarding
